### ISSUE TITLE
application/pipeline

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#12]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by wg102** [comment]
The changes is to use our own version of the pipelines. This version just got updated because of a vulnerability as well, and fix the issue with the internationalization not finding the source files for en and fr. See https://github.com/StatCan/kubeflow-pipelines/issues/12 for the details

**Comment by wg102** [comment]
I am getting an issue where the application app Health keeps switching between _Healthy_ and _Progressing_ and therefore the pipelines between showing up as expected and "No healthy upstream". I am unsure if it's just something that takes extra time (20 min and still ongoing issue), or an actual problem that something is not set correctly

**Comment by rohank07** [comment]
Successfully tested pipelines locally, creating an experiment using the demo pipelines. At the moment we are unable to test creating pipelines from jupyter-notebooks. Additionally there seems to be a Request Header error which we believe is because our testing environment cuts a lot of corners when compared to dev/prod. This is another reason which suggests that we should just try to test on dev. There is an issue with kfp not being able to connect to the pipeline  (Jira ticket created). We will be able to test this when kfp on Prod/Dev is resolved. 


![image](https://user-images.githubusercontent.com/28408586/135911126-4080fd20-c9c5-4285-a0df-27bca5b3f373.png)
