### ISSUE TITLE
Argoflow manifest - oidc-authservice

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#21]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by Jose-Matsuda** [comment]
Ok first thing I do is figure out what https://github.com/StatCan/aaw-argoflow-azure/tree/manifest-rebase/distribution/oidc-auth/base this is and compare to what they have in kubeflow/manifests 1.3  [branch](https://github.com/kubeflow/manifests/tree/v1.3-branch/common/oidc-authservice/overlays/ibm-storage-config). If I confirm that this is the same THEN I look at moving from 1.2 (what we have [here](https://github.com/StatCan/aaw-kubeflow-manifest/tree/master/kustomize/oidc-authservice) and upstream is [here](https://github.com/kubeflow/manifests/blob/v1.2-branch/stacks/azure/application/oidc-authservice/kustomization.yaml)  to 1.3 which is ~~[here](https://github.com/kubeflow/manifests/tree/v1.3-branch/common/oidc-authservice/overlays/ibm-storage-config)~~ which is also said in the [README](https://github.com/kubeflow/manifests/tree/v1.3-branch#oidc-authservice) see the edit below, there are actually quite a few things in kubeflow/manifests that have something to do with auth, here's another one under [contrib](https://github.com/kubeflow/manifests/tree/v1.3-branch/contrib) for example.

EDIT 12/10/2021 
ACTUALLY our upstream for 1.3 may be here instead of under `common`
https://github.com/kubeflow/manifests/blob/v1.3-branch/distributions/stacks/azure/application/oidc-authservice/kustomization.yaml <-- this is much closer aligned to what we have in 1.2 it seems

^ having said that, there's something fishy where the resources under the [oidc-authservice](https://github.com/kubeflow/manifests/blob/v1.3-branch/distributions/stacks/azure/application/oidc-authservice/kustomization.yaml#L5) here seems to point to a directory which does not exist?

**Comment by Jose-Matsuda** [comment]
These 3 
![image](https://user-images.githubusercontent.com/23174198/136984756-4bdadcf2-e7a8-4df4-bf25-4aebe14d2b06.png)
point to their respective resources under https://github.com/StatCan/aaw-argoflow-azure/tree/manifest-rebase/distribution/oidc-auth

The 3 files under argocd-applications are the same aside from the path, and the `keycloak` and `dex` have a `namespace: auth` under `spec/destination` whereas the file that references `base` does not have this entry.

So I suppose the next step here is as mentioned above, go through these three paths of `base`, `keycloak`, and `dex` and find out if it corresponds to anything in kubeflow/manifests [1.3](https://github.com/kubeflow/manifests/tree/v1.3-branch/common/oidc-authservice) or at least find out what they are and used for.

^ These files seem different enough from what is seen in `/common/oidc-authservice/base` to warrant oidc-authservice. Dex is just `Dex` its own [thing](https://github.com/kubeflow/manifests#dex)and `keycloak` is also its own [thing](https://github.com/kubeflow/manifests/search?q=keycloak)

**Comment by Jose-Matsuda** [comment]
## IMPORTANT 
Replying in specific to this one 
> Ok first thing I do is figure out what https://github.com/StatCan/aaw-argoflow-azure/tree/manifest-rebase/distribution/oidc-
> 
> ^ having said that, there's something fishy where the resources under the [oidc-authservice](https://github.com/kubeflow/manifests/blob/v1.3-branch/distributions/stacks/azure/application/oidc-authservice/kustomization.yaml#L5) here seems to point to a directory which does not exist?


I now think we need to actually use the one under `manifests/common/oidc-authservice/base` because 
A) The docs reference this version.
B) Following the path that we use of `../../.cache/manifests/manifests-1.2-branch/stacks/azure/application/oidc-authservice` when you look in the kustomize under that path, it references `../../../../istio/oidc-authservice/overlays/application` and that [kustomize](https://github.com/kubeflow/manifests/blob/v1.2-branch/istio/oidc-authservice/overlays/application/kustomization.yaml#L3) references a [base](https://github.com/kubeflow/manifests/tree/v1.2-branch/istio/oidc-authservice/base) which looks very familiar to what we is in the `common/oidc-authservice/base` area. 

So essentially from B the amount of 'customization' from the `azure/application/oidc-authservice` is minimal and I think we can skip that step and point to `common/.../base` 

Another nice thing is that in 1.4 onwards the distribution folder is removed to a different spot (not under manifests) so moving from 1.3 to 1.4 should not be a huge problem.

**Comment by Jose-Matsuda** [comment]
The first notable difference that I ran into is in the `statefulset.yaml`
Where ours differs from upstream at line 25 where they use envFrom instead of just env
A little breakdown of the differences at each line is
```
 env: #in 1.3 changed to use envFrom
        # uses the configMapGenerator in the kustomize (which uses the params.env)
        # we can change this to just use envFrom and use oidc-authservice-parameters
        #just neeed to ensure that the key and values are the same 
        #good means found in our configmap.yaml,  ??? means ???
          - name: USERID_HEADER
            value: $(userid-header) #good
          - name: USERID_PREFIX
            value: $(userid-prefix) #good
          - name: USERID_CLAIM
            value: preferred_username #???? is under user_id claim in 1.3 params.env but has a different value
            # they have USERID_CLAIM=email. this is the same in 1.2 so preferred_username may be specific to us
          - name: OIDC_PROVIDER
            value: $(oidc_provider) #good 
          - name: OIDC_AUTH_URL
            value: $(oidc_auth_url) #good 
          - name: OIDC_SCOPES
            value: "profile email" #???? is in 1.3 params.env but has different value of profile email groups
            # (1.2 also had profile email groups fwiw so maybe specific to us)
          - name: REDIRECT_URL
            value: $(oidc_redirect_uri) #good
          - name: SKIP_AUTH_URI
            value: $(skip_auth_uri) #good
          - name: PORT
            value: "8080" #??? is again in params.env, they keep as 8080
          - name: CLIENT_ID
            value: $(client_id) #good
          - name: CLIENT_SECRET
            value: $(application_secret) #good
          - name: STORE_PATH
            value: /var/lib/authservice/data.db # ??? they have this as well and its the same 
```

So if we want to, we can copy their use of fromEnv but replace in our configmap.yaml our specific settings so that there's only one place to look for them.

**Comment by Jose-Matsuda** [comment]
Ok after getting the correct reference I now get something forever out of sync
![image](https://user-images.githubusercontent.com/23174198/137388983-490d5251-7ef6-4c2c-b140-5bc2e077b33d.png)
where it is like this for all the resources 
![image](https://user-images.githubusercontent.com/23174198/137389012-326aece7-3cd1-4bb1-8cca-1f8d5e7086f7.png)

Found these
![image](https://user-images.githubusercontent.com/23174198/137390086-c26b7461-bb75-45b0-a991-b35b1b5e71ab.png)

Ok that first error is an indenting issue.

Ok after fixing that first issue im now somewhat stuck on the next one I dont get it. It comes from upstream the envoyfilter upstream which should work (maybe its because of Istio 1.10)
.

**Comment by Jose-Matsuda** [comment]
New comment because actual progress
![image](https://user-images.githubusercontent.com/23174198/137501782-fec01d69-9eaf-492e-8395-b5ee1b8714a0.png)
![image](https://user-images.githubusercontent.com/23174198/137501812-2dfefc39-3cc4-472a-a4e4-9ea07875c474.png)

It seems like there was some kind of issue in the indenting in the envoy-filter from 1.3, why that is I don't know but indenting this block on [line 13](https://github.com/kubeflow/manifests/blob/v1.3-branch/common/oidc-authservice/base/envoy-filter.yaml#L13) to put `listener` under context and not match made it pass.
![image](https://user-images.githubusercontent.com/23174198/137501968-188720c8-aeb0-47b9-ab95-ecfafeb6f558.png)


Why the level is at `match` and not `context` I don't really understand as even as early as [istio1.3](https://istio.io/v1.3/docs/reference/config/networking/v1alpha3/envoy-filter/) its under `context` and when I do try to look at earlier versions of istio like [1.1](https://istio.io/v1.1/docs/reference/config/networking/v1alpha3/envoy-filter/) it has the oidc-authservice kubeflow/manifest 1.2 branch of using `workloadLabels`


That last error is resolved by removing the "subFilter" section on line 17 that comes after filter. 
![image](https://user-images.githubusercontent.com/23174198/137515590-4aab7833-4dcd-42df-9ff2-f4dec8bf8899.png)

**Comment by Jose-Matsuda** [comment]
The pod seems unhealthy even after kind loading the image but I'll look into the above error first
![image](https://user-images.githubusercontent.com/23174198/137511640-bf44a2a5-47cb-40a3-a7d0-70d338e78d60.png)

I think its because of `imagePullSecrets` on line 37 and 38.

I will test what will happen if I comment out that `imagePullSecrets` line, if it passes great. I will just need to figure out this [bit](https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod)

**Comment by Jose-Matsuda** [comment]
For resource specific and change specific comments please refer to the PR https://github.com/StatCan/aaw-argoflow-azure/pull/37 as I will be leaving comments there.
