### ISSUE TITLE
Argoflow Manifest application/mpi-job

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#29]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by Jose-Matsuda** [comment]
May leave this for now. Minimize work to deploy as not necessarily being used at the moment. Will  leave everything in but in commented form.

**Comment by rohank07** [comment]
![image](https://user-images.githubusercontent.com/28408586/139074792-783858f5-2d17-47ba-8bf4-d7c955cd0b1c.png)
![image](https://user-images.githubusercontent.com/28408586/139076714-47400fa3-62c3-4e5c-8551-798a83e24d63.png)


Pod fails `Back-off restarting failed container`. Since this is second-priority, we wiil revisit this and focus on other priority deployments for the time being.
